application: foundedinsouthafrica
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /admin
  script: main.app
  login: admin
- url: /dashboard
  script: main.app
  login: admin
- url: /dashboard2
  script: main.app
  login: admin
- url: /dashboard/startup_emails
  script: main.app
  login: admin
- url: /dashboard/earlyadopter_emails
  script: main.app
  login: admin
- url: /dashboard/startups
  script: main.app
  login: admin
- url: /dashboard/feature
  script: main.app
  login: admin
- url: /dashboard/feature_edit/.*
  script: main.app
  login: admin
- url: /dashboard/featured_articles
  script: main.app
  login: admin
- url: /dashboard/logo
  script: main.app
  login: admin

- url: /static
  static_dir: static
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: PIL
  version: latest
- name: ssl
  version: latest
